### ISSUE TITLE
Fail to namespacing `import` identifier (was: Cannot bootstrap NMosh with GHA artifact)

### ISSUE THREAD

**Issue by okuoku** [higepon/mosh#204]
At: https://github.com/higepon/mosh/commit/27c1c717b2cbf14ff7de2ca3339306d61ee73729

```
Mosh R6RS scheme interpreter, version 0.2.8-rc5 (27c1c71 Wed, 19 Oct 2022 12:51:35 +0000)
```

When using `source-ubuntu-latest.zip` of GHA artifact, it cannot bootstrap NMosh, at least on my side. I have narrowed error is from `misc/scripts/gen-nmosh-bootstrap.sps`:

```
$ mosh --disable-acc --verbose --loadpath=lib misc/scripts/gen-nmosh-bootstrap.sps
 Condition components:
 1. &who           who: import
 2. &message       message: "invalid sub-version spec"
 3. &syntax        form: '((rnrs))
                   subform: (rnrs)

 Exception:
     error in raise: returned from non-continuable exception

 Stack trace:
    1. throw: <subr>
    2. (raise c):  baselib.scm:950
    3. (map-1 proc lst):  baselib.scm:109
    4. (lambda (sub*) ...):  psyntax.scm:11
    5. (lambda (version-spec*) ...):  psyntax.scm:11
    6. (lambda (x x*) ...):  psyntax.scm:11
    7. (import-library spec*):  psyntax.scm:11
    8. (lambda (imp*) ...):  psyntax.scm:11
    9. (lambda (imp*) ...):  psyntax.scm:11
    10. (lambda () ...):  psyntax.scm:11
    11. (dynamic-wind in body out):  baselib.scm:786
    12. (lambda (P9bc6 P9bc8) ...):  psyntax.scm:11
    13. (compile-r6rs-top-level x*):  psyntax.scm:11
```

**Comment by okuoku** [comment]
Reduced further:

```scheme
(import (rnrs)
        (yuni util library-writer))

(make library-spec
      (import '((rnrs))))
```

It seems `import` is now treated as bound syntax.

**Comment by okuoku** [comment]
Reduced further:

```scheme
(import (rnrs))

(define-syntax pick
  (syntax-rules ()
    ((_ (dummy here))
     here)))

(pick (import '((rnrs))))
```

Unlike R7RS, R6RS library language(`import` `export` `library` ...) shouldn't be visible outside of library/program declaration because it is not bound in any standard libraries. And even on R7RS, these should be treated as just a bound identifier here.

**Comment by higepon** [comment]
Fixed in https://github.com/higepon/mosh/pull/207.
Thank you for the reproduce steps. It helps a lot!

**Comment by okuoku** [comment]
Hmm, it is not fixed:

```scheme
oku@ubuntults:~/repos/mosh$ cat check.sps
(import (rnrs))

(define-syntax pick
  (syntax-rules ()
    ((_ (dummy here))
     here)))

(pick (import '((rnrs))))

oku@ubuntults:~/repos/mosh$ mosh check.sps
 Condition components:
 1. &message                  message: "invalid syntax"
 2. &syntax                   form: (pick import '((rnrs)))
                              subform: #f
 3. &source-information       file-name: "<transcoded-textual-input-port <binary-input-port check.sps>>"
                              line: 10

 Exception:
     error in raise: returned from non-continuable exception

 Stack trace:
    1. throw: <subr>
    2. (raise c):  baselib.scm:950
    3. (do-macro-call transformer expr rib):  psyntax.scm:11
    4. (lambda (P966a P966c P966e) ...):  psyntax.scm:11
    5. (lambda (P966a P966c P966e) ...):  psyntax.scm:11
    6. (chi-library-internal e* rib top?):  psyntax.scm:11
    7. (lambda () ...):  psyntax.scm:11
    8. (dynamic-wind in body out):  baselib.scm:786
    9. (dynamic-wind in body out):  baselib.scm:786
    10. (lambda (P9bce P9bd0) ...):  psyntax.scm:11
    11. (compile-r6rs-top-level x*):  psyntax.scm:11


oku@ubuntults:~/repos/mosh$ mosh -V
Mosh R6RS scheme interpreter, version 0.2.8-rc5 (4446b86 Thu, 20 Oct 2022 08:40:20 +0900)

(version "0.2.8-rc5")
(scheme.id mosh)
(languages scheme r6rs r7rs)
(encodings utf-8)
(website "https://mosh.monaos.org/")
```

Tested at: https://github.com/higepon/mosh/commit/4446b8640dc9b103e7cdb3b162756541e3cc477d

**Comment by higepon** [comment]
Thanks. What is the expected behaviour there?

> form: (pick import '((rnrs)))

Mosh is not is touching import here (I think).

**Comment by okuoku** [comment]
> What is the expected behaviour there?

Evaluate the program without any error. At least, Chez runs the script flawlessly.

```scheme
(pick (import '((rnrs)))) ;; => ((rnrs))
```

> Mosh is not is touching import here (I think).

So it should not affect execution and should not raise any exception if so. To reiterate the point when I reported original issue, `import` is not exported in `(rnrs)` so it must unbound and should never be treated as a syntax.

`pick` in reproducing example trying to just skip and return portion of the argument. For example, replacing `import` to `import0` make it working even on https://github.com/higepon/mosh/commit/4446b8640dc9b103e7cdb3b162756541e3cc477d

```scheme
oku@ubuntults:~$ cat check.sps
(import (rnrs))

(define-syntax pick
  (syntax-rules ()
    ((_ (dummy here))
     here)))

(display (pick (import0 '((rnrs))))) (newline)
oku@ubuntults:~$ /opt/yunibase/current/mosh/bin/mosh check.sps
((rnrs))
```

**Comment by higepon** [comment]
Thank you. I realized that the first error reported ```message: "invalid sub-version spec"``` was my bug in R7RS -> R6RS converter.
The second error is (I believe) in psyntax and it is not a new bug. It has been there. So I'm not sure if there's easy fix there.

Is the psyntax bug blocking you? Any workaround you can have there?
I'll look into the psyntax issue.

**Comment by okuoku** [comment]
> The second error is (I believe) in psyntax and it is not a new bug.

The code like this have been used for a while because it's part of NMosh bootstrap. So I think it's a regression -- at least  https://github.com/higepon/mosh/tree/0c912605fab6abac4cc0245f950bab944cc5bb32 was okay, I haven't tested `pick` example there though.

> Any workaround you can have there?

I think I can workaround by changing bootstrap script; just avoiding use of `import` symbol in expand phase.

**Comment by higepon** [comment]
I installed the current head and run the bootstrap. It finished with exit code 0 + warnings.  Do think the issue was fixed?
```
 mosh --disable-acc --verbose --loadpath=lib misc/scripts/gen-nmosh-bootstrap.sps
WARNING: library (mosh pp) has an inconsistent dependency on library (rnrs mutable-strings); file /root/mosh.git/lib/mosh/pp.ss will be recompiled from source. 
WARNING: library (srfi :8 receive) has an inconsistent dependency on library (rnrs); file /root/mosh.git/lib/srfi/%3a8/receive.sls will be recompiled from source. 
WARNING: library (srfi :8) has an inconsistent dependency on library (srfi :8 receive); file /root/mosh.git/lib/srfi/%3a8.mosh.sls will be recompiled from source. 
WARNING: library (yuni util invalid-form) has an inconsistent dependency on library (rnrs); file /root/mosh.git/lib/yuni/util/invalid-form.sls will be recompiled from source. 
WARNING: library (yuni core) has an inconsistent dependency on library (yuni util invalid-form); file /root/mosh.git/lib/yuni/core.sls will be recompiled from source. 
WARNING: library (yuni miniobj base) has an inconsistent dependency on library (rnrs); file /root/mosh.git/lib/yuni/miniobj/base.sls will be recompiled from source. 
WARNING: library (yuni miniobj) has an inconsistent dependency on library (yuni miniobj base); file /root/mosh.git/lib/yuni/miniobj.sls will be recompiled from source. 
WARNING: library (yuni miniobj rnrs) has an inconsistent dependency on library (rnrs); file /root/mosh.git/lib/yuni/miniobj/rnrs.sls will be recompiled from source. 
WARNING: library (yuni compat simple-struct) has an inconsistent dependency on library (system); file /root/mosh.git/lib/yuni/compat/simple-struct.mosh.sls will be recompiled from source. 
WARNING: library (yuni miniobj minitype) has an inconsistent dependency on library (yuni compat simple-struct); file /root/mosh.git/lib/yuni/miniobj/minitype.sls will be recompiled from source. 
WARNING: library (yuni util library-writer) has an inconsistent dependency on library (yuni core); file /root/mosh.git/lib/yuni/util/library-writer.sls will be recompiled from source. 
WARNING: library (shorten helper) has an inconsistent dependency on library (rnrs); file /root/mosh.git/lib/shorten/helper.ss will be recompiled from source. 
WARNING: library (shorten) has an inconsistent dependency on library (shorten helper); file /root/mosh.git/lib/shorten.ss will be recompiled from source. 
WARNING: library (mosh file) has an inconsistent dependency on library (system); file /root/mosh.git/lib/mosh/file.ss will be recompiled from source. 
WARNING: library (yuni compat file-ops) has an inconsistent dependency on library (mosh file); file /root/mosh.git/lib/yuni/compat/file-ops.mosh.sls will be recompiled from source. 
WARNING: library (yuni util files) has an inconsistent dependency on library (yuni compat file-ops); file /root/mosh.git/lib/yuni/util/files.sls will be recompiled from source. 
WARNING: library (match) has an inconsistent dependency on library (rnrs mutable-pairs); file /root/mosh.git/lib/match.ss will be recompiled from source. 
WARNING: library (nmosh bootstrap stubs) has an inconsistent dependency on library (match); file /root/mosh.git/lib/nmosh/bootstrap/stubs.sls will be recompiled from source. 
WARNING: library (srfi :1 lists) has an inconsistent dependency on library (rnrs mutable-pairs); file /root/mosh.git/lib/srfi/%3a1/lists.sls will be recompiled from source. 
WARNING: library (srfi :1) has an inconsistent dependency on library (srfi :1 lists); file /root/mosh.git/lib/srfi/%3a1.mosh.sls will be recompiled from source. 
WARNING: library (srfi :38 with-shared-structure) has an inconsistent dependency on library (rnrs); file /root/mosh.git/lib/srfi/%3a38/with-shared-structure.mosh.sls will be recompiled from source. 
WARNING: library (srfi :48 intermediate-format-strings) has an inconsistent dependency on library (srfi :38 with-shared-structure); file /root/mosh.git/lib/srfi/%3a48/intermediate-format-strings.sls will be recompiled from source. 
WARNING: library (srfi :48 intermediate-format-strings compat) has an inconsistent dependency on library (mosh pp); file /root/mosh.git/lib/srfi/%3a48/intermediate-format-strings/compat.mosh.sls will be recompiled from source. 
WARNING: library (srfi :6 basic-string-ports compat) has an inconsistent dependency on library (system); file /root/mosh.git/lib/srfi/%3a6/basic-string-ports/compat.mosh.sls will be recompiled from source. 
WARNING: library (srfi :6 basic-string-ports) has an inconsistent dependency on library (srfi :6 basic-string-ports compat); file /root/mosh.git/lib/srfi/%3a6/basic-string-ports.sls will be recompiled from source. 
WARNING: library (srfi :48) has an inconsistent dependency on library (srfi :48 intermediate-format-strings); file /root/mosh.git/lib/srfi/%3a48.mosh.sls will be recompiled from source. 
WARNING: library (yuni util binding-constructs) has an inconsistent dependency on library (rnrs); file /root/mosh.git/lib/yuni/util/binding-constructs.sls will be recompiled from source. 
$ echo $?
0
```

**Comment by higepon** [comment]
Hold on still investigating.

**Comment by okuoku** [comment]
How does `mosh -V` say? My build is built with https://github.com/higepon/mosh/actions/runs/3285750032 artifact and still show the same issue.

```
Mosh R6RS scheme interpreter, version 0.2.8-rc5 (4446b86 Thu, 20 Oct 2022 08:40:20 +0900)
```

```
$ mosh --disable-acc --verbose --loadpath=lib misc/scripts/gen-nmosh-bootstrap.sps
 Condition components:
 1. &message       message: "invalid syntax"
 2. &syntax        form: (make-apply-rule1! new-object import)
                   subform: #f

 Exception:
     error in raise: returned from non-continuable exception

 Stack trace:
    1. throw: <subr>
    2. (raise c):  baselib.scm:950
    3. (do-macro-call transformer expr rib):  psyntax.scm:11
    4. (lambda (P944e P9450 P9452) ...):  psyntax.scm:11
    5. (chi-expr* e* r mr):  psyntax.scm:11
    6. (chi-expr* e* r mr):  psyntax.scm:11
    7. (chi-expr* e* r mr):  psyntax.scm:11
    8. (chi-expr* e* r mr):  psyntax.scm:11
    9. (chi-expr* e* r mr):  psyntax.scm:11
    10. (lambda (P9582 P9584 P9586 P9588 P958a P958c P958e P9590) ...):  psyntax.scm:11
    11. (lambda (lhs* rhs* b b*) ...):  psyntax.scm:11
    12. (lambda (lhs* rhs* b b*) ...):  psyntax.scm:11
    13. (chi-expr* e* r mr):  psyntax.scm:11
    14. (chi-expr* e* r mr):  psyntax.scm:11
    15. (chi-expr* e* r mr):  psyntax.scm:11
    16. (lambda (rator rands) ...):  psyntax.scm:11
    17. (lambda (rator rands) ...):  psyntax.scm:11
    18. (chi-expr* e* r mr):  psyntax.scm:11
    19. (lambda (P9582 P9584 P9586 P9588 P958a P958c P958e P9590) ...):  psyntax.scm:11
    20. (lambda (lhs* rhs* b b*) ...):  psyntax.scm:11
      ... (more stack dump truncated)
```

and patching `import` to `import0` make it work:

```diff
diff --git a/lib/yuni/util/library-writer.sls b/lib/yuni/util/library-writer.sls
index 799c863a..83c50ad7 100644
--- a/lib/yuni/util/library-writer.sls
+++ b/lib/yuni/util/library-writer.sls
@@ -9,7 +9,7 @@
                  (yuni core))

 (define* library-spec
-  (name export import comment code))
+  (name export import0 comment code))

 (define* (write-library output (library-spec))
   (define (prepare-port p)
@@ -33,7 +33,7 @@
     ;; FIXME: implement-it..
     "")

-  (let-with library-spec (export import comment code name)
+  (let-with library-spec (export import0 comment code name)
     (define p (prepare-port output))
     (display (format-comment (if (string? comment)
                                (list comment)
@@ -43,7 +43,7 @@
     (write name p)
     (newline p)
     (display (tabbed-out (cons 'export export)) p)
-    (display (tabbed-out (cons 'import import)) p)
+    (display (tabbed-out (cons 'import import0)) p)
     (for-each (^e (pp e p)) code)
     (display ")" p)
     (close-port p)))
diff --git a/misc/scripts/gen-nmosh-bootstrap.sps b/misc/scripts/gen-nmosh-bootstrap.sps
index 1fbf5dd1..d5d7ca29 100644
--- a/misc/scripts/gen-nmosh-bootstrap.sps
+++ b/misc/scripts/gen-nmosh-bootstrap.sps
@@ -99,7 +99,7 @@
                  (make library-spec
                    (name '(nmosh boot src-config))
                    (export '(src-free-vars instructions))
-                   (import '((rnrs)))
+                   (import0 '((rnrs)))
                    (code `((define src-free-vars (quote ,free-vars))
                            (define instructions (quote ,instructions))))
                    (comment '("nothing"))))
@@ -108,7 +108,7 @@
                    (make library-spec
                          (name '(nmosh boot compiler))
                          (export (remq 'top-level-macros (export-all proc)))
-                         (import '((except (rnrs)
+                         (import0 '((except (rnrs)
                                            command-line
                                            do)
                                    (rnrs mutable-pairs)
@@ -135,7 +135,7 @@
                      (make library-spec
                            (name '(nmosh boot compiler-macro))
                            (export (export-all macro-code))
-                           (import '((for (except (rnrs) do) run expand)
+                           (import0 '((for (except (rnrs) do) run expand)
                                      (for (match) expand run)
                                      (for (yuni compat gensym) expand)
                                      (nmosh util define-macro)
@@ -150,7 +150,7 @@
                    (make library-spec
                      (name '(nmosh boot vm))
                      (export '(vm/apply))
-                     (import '((except (rnrs) do)
+                     (import0 '((except (rnrs) do)
                                (only (srfi :1) first second third append-map)
                                (only (nmosh boot compiler) $map1 $lvar compile-partial pass4)
                                (mosh control)
@@ -167,7 +167,7 @@
                      (make library-spec
                        (name '(nmosh boot vm-macro))
                        (export (export-all macro-code))
-                       (import '((for (except (rnrs) do) run expand)
+                       (import0 '((for (except (rnrs) do) run expand)
                                  (for (match) expand run)
                                  (for (nmosh util syntax-error) expand)
                                  (nmosh util define-macro)))
```

**Comment by higepon** [comment]
Sorry still investigating. I think you're right. Something is wrong.

**Comment by higepon** [comment]
I apologize that it was my fault.
It should be fixed in https://github.com/higepon/mosh/pull/208. The test case I added was wrong and couldn't catch the issue.
